/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReceiptTokenRouteImport } from './routes/receipt.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as BillPdfSha256RouteImport } from './routes/bill.$pdfSha256'
import { Route as ApiCronRouteImport } from './routes/api.cron'
import { Route as ApiAiRouteImport } from './routes/api.ai'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as AppRecurringBillsRouteImport } from './routes/_app.recurring-bills'
import { Route as AppHousematesRouteImport } from './routes/_app.housemates'
import { Route as AppBillsRouteImport } from './routes/_app.bills'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as ApiPdfsPdfSha256RouteImport } from './routes/api.pdfs.$pdfSha256'
import { Route as ApiHooksWhatsappRouteImport } from './routes/api.hooks.whatsapp'
import { Route as ApiHooksUpRouteImport } from './routes/api.hooks.up'
import { Route as ApiHooksEmailRouteImport } from './routes/api.hooks.email'
import { Route as ApiCardsPdfSha256RouteImport } from './routes/api.cards.$pdfSha256'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiCardsReceiptTokenRouteImport } from './routes/api.cards.receipt.$token'
import { Route as ApiCardsPayTokenRouteImport } from './routes/api.cards.pay.$token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptTokenRoute = ReceiptTokenRouteImport.update({
  id: '/receipt/$token',
  path: '/receipt/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BillPdfSha256Route = BillPdfSha256RouteImport.update({
  id: '/bill/$pdfSha256',
  path: '/bill/$pdfSha256',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronRoute = ApiCronRouteImport.update({
  id: '/api/cron',
  path: '/api/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecurringBillsRoute = AppRecurringBillsRouteImport.update({
  id: '/recurring-bills',
  path: '/recurring-bills',
  getParentRoute: () => AppRoute,
} as any)
const AppHousematesRoute = AppHousematesRouteImport.update({
  id: '/housemates',
  path: '/housemates',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsRoute = AppBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const ApiPdfsPdfSha256Route = ApiPdfsPdfSha256RouteImport.update({
  id: '/api/pdfs/$pdfSha256',
  path: '/api/pdfs/$pdfSha256',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksWhatsappRoute = ApiHooksWhatsappRouteImport.update({
  id: '/api/hooks/whatsapp',
  path: '/api/hooks/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksUpRoute = ApiHooksUpRouteImport.update({
  id: '/api/hooks/up',
  path: '/api/hooks/up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHooksEmailRoute = ApiHooksEmailRouteImport.update({
  id: '/api/hooks/email',
  path: '/api/hooks/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsPdfSha256Route = ApiCardsPdfSha256RouteImport.update({
  id: '/api/cards/$pdfSha256',
  path: '/api/cards/$pdfSha256',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsReceiptTokenRoute = ApiCardsReceiptTokenRouteImport.update({
  id: '/api/cards/receipt/$token',
  path: '/api/cards/receipt/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardsPayTokenRoute = ApiCardsPayTokenRouteImport.update({
  id: '/api/cards/pay/$token',
  path: '/api/cards/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRoute
  '/bills': typeof AppBillsRoute
  '/housemates': typeof AppHousematesRoute
  '/recurring-bills': typeof AppRecurringBillsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/ai': typeof ApiAiRoute
  '/api/cron': typeof ApiCronRoute
  '/bill/$pdfSha256': typeof BillPdfSha256Route
  '/pay/$token': typeof PayTokenRoute
  '/receipt/$token': typeof ReceiptTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cards/$pdfSha256': typeof ApiCardsPdfSha256Route
  '/api/hooks/email': typeof ApiHooksEmailRoute
  '/api/hooks/up': typeof ApiHooksUpRoute
  '/api/hooks/whatsapp': typeof ApiHooksWhatsappRoute
  '/api/pdfs/$pdfSha256': typeof ApiPdfsPdfSha256Route
  '/api/cards/pay/$token': typeof ApiCardsPayTokenRoute
  '/api/cards/receipt/$token': typeof ApiCardsReceiptTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ai': typeof AppAiRoute
  '/bills': typeof AppBillsRoute
  '/housemates': typeof AppHousematesRoute
  '/recurring-bills': typeof AppRecurringBillsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/ai': typeof ApiAiRoute
  '/api/cron': typeof ApiCronRoute
  '/bill/$pdfSha256': typeof BillPdfSha256Route
  '/pay/$token': typeof PayTokenRoute
  '/receipt/$token': typeof ReceiptTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cards/$pdfSha256': typeof ApiCardsPdfSha256Route
  '/api/hooks/email': typeof ApiHooksEmailRoute
  '/api/hooks/up': typeof ApiHooksUpRoute
  '/api/hooks/whatsapp': typeof ApiHooksWhatsappRoute
  '/api/pdfs/$pdfSha256': typeof ApiPdfsPdfSha256Route
  '/api/cards/pay/$token': typeof ApiCardsPayTokenRoute
  '/api/cards/receipt/$token': typeof ApiCardsReceiptTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/bills': typeof AppBillsRoute
  '/_app/housemates': typeof AppHousematesRoute
  '/_app/recurring-bills': typeof AppRecurringBillsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/ai': typeof ApiAiRoute
  '/api/cron': typeof ApiCronRoute
  '/bill/$pdfSha256': typeof BillPdfSha256Route
  '/pay/$token': typeof PayTokenRoute
  '/receipt/$token': typeof ReceiptTokenRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/cards/$pdfSha256': typeof ApiCardsPdfSha256Route
  '/api/hooks/email': typeof ApiHooksEmailRoute
  '/api/hooks/up': typeof ApiHooksUpRoute
  '/api/hooks/whatsapp': typeof ApiHooksWhatsappRoute
  '/api/pdfs/$pdfSha256': typeof ApiPdfsPdfSha256Route
  '/api/cards/pay/$token': typeof ApiCardsPayTokenRoute
  '/api/cards/receipt/$token': typeof ApiCardsReceiptTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/ai'
    | '/bills'
    | '/housemates'
    | '/recurring-bills'
    | '/api/$'
    | '/api/ai'
    | '/api/cron'
    | '/bill/$pdfSha256'
    | '/pay/$token'
    | '/receipt/$token'
    | '/api/auth/$'
    | '/api/cards/$pdfSha256'
    | '/api/hooks/email'
    | '/api/hooks/up'
    | '/api/hooks/whatsapp'
    | '/api/pdfs/$pdfSha256'
    | '/api/cards/pay/$token'
    | '/api/cards/receipt/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ai'
    | '/bills'
    | '/housemates'
    | '/recurring-bills'
    | '/api/$'
    | '/api/ai'
    | '/api/cron'
    | '/bill/$pdfSha256'
    | '/pay/$token'
    | '/receipt/$token'
    | '/api/auth/$'
    | '/api/cards/$pdfSha256'
    | '/api/hooks/email'
    | '/api/hooks/up'
    | '/api/hooks/whatsapp'
    | '/api/pdfs/$pdfSha256'
    | '/api/cards/pay/$token'
    | '/api/cards/receipt/$token'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/ai'
    | '/_app/bills'
    | '/_app/housemates'
    | '/_app/recurring-bills'
    | '/api/$'
    | '/api/ai'
    | '/api/cron'
    | '/bill/$pdfSha256'
    | '/pay/$token'
    | '/receipt/$token'
    | '/api/auth/$'
    | '/api/cards/$pdfSha256'
    | '/api/hooks/email'
    | '/api/hooks/up'
    | '/api/hooks/whatsapp'
    | '/api/pdfs/$pdfSha256'
    | '/api/cards/pay/$token'
    | '/api/cards/receipt/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiCronRoute: typeof ApiCronRoute
  BillPdfSha256Route: typeof BillPdfSha256Route
  PayTokenRoute: typeof PayTokenRoute
  ReceiptTokenRoute: typeof ReceiptTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCardsPdfSha256Route: typeof ApiCardsPdfSha256Route
  ApiHooksEmailRoute: typeof ApiHooksEmailRoute
  ApiHooksUpRoute: typeof ApiHooksUpRoute
  ApiHooksWhatsappRoute: typeof ApiHooksWhatsappRoute
  ApiPdfsPdfSha256Route: typeof ApiPdfsPdfSha256Route
  ApiCardsPayTokenRoute: typeof ApiCardsPayTokenRoute
  ApiCardsReceiptTokenRoute: typeof ApiCardsReceiptTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$token': {
      id: '/receipt/$token'
      path: '/receipt/$token'
      fullPath: '/receipt/$token'
      preLoaderRoute: typeof ReceiptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill/$pdfSha256': {
      id: '/bill/$pdfSha256'
      path: '/bill/$pdfSha256'
      fullPath: '/bill/$pdfSha256'
      preLoaderRoute: typeof BillPdfSha256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron': {
      id: '/api/cron'
      path: '/api/cron'
      fullPath: '/api/cron'
      preLoaderRoute: typeof ApiCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recurring-bills': {
      id: '/_app/recurring-bills'
      path: '/recurring-bills'
      fullPath: '/recurring-bills'
      preLoaderRoute: typeof AppRecurringBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/housemates': {
      id: '/_app/housemates'
      path: '/housemates'
      fullPath: '/housemates'
      preLoaderRoute: typeof AppHousematesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills': {
      id: '/_app/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof AppBillsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/pdfs/$pdfSha256': {
      id: '/api/pdfs/$pdfSha256'
      path: '/api/pdfs/$pdfSha256'
      fullPath: '/api/pdfs/$pdfSha256'
      preLoaderRoute: typeof ApiPdfsPdfSha256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/whatsapp': {
      id: '/api/hooks/whatsapp'
      path: '/api/hooks/whatsapp'
      fullPath: '/api/hooks/whatsapp'
      preLoaderRoute: typeof ApiHooksWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/up': {
      id: '/api/hooks/up'
      path: '/api/hooks/up'
      fullPath: '/api/hooks/up'
      preLoaderRoute: typeof ApiHooksUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hooks/email': {
      id: '/api/hooks/email'
      path: '/api/hooks/email'
      fullPath: '/api/hooks/email'
      preLoaderRoute: typeof ApiHooksEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards/$pdfSha256': {
      id: '/api/cards/$pdfSha256'
      path: '/api/cards/$pdfSha256'
      fullPath: '/api/cards/$pdfSha256'
      preLoaderRoute: typeof ApiCardsPdfSha256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards/receipt/$token': {
      id: '/api/cards/receipt/$token'
      path: '/api/cards/receipt/$token'
      fullPath: '/api/cards/receipt/$token'
      preLoaderRoute: typeof ApiCardsReceiptTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cards/pay/$token': {
      id: '/api/cards/pay/$token'
      path: '/api/cards/pay/$token'
      fullPath: '/api/cards/pay/$token'
      preLoaderRoute: typeof ApiCardsPayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppBillsRoute: typeof AppBillsRoute
  AppHousematesRoute: typeof AppHousematesRoute
  AppRecurringBillsRoute: typeof AppRecurringBillsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppBillsRoute: AppBillsRoute,
  AppHousematesRoute: AppHousematesRoute,
  AppRecurringBillsRoute: AppRecurringBillsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAiRoute: ApiAiRoute,
  ApiCronRoute: ApiCronRoute,
  BillPdfSha256Route: BillPdfSha256Route,
  PayTokenRoute: PayTokenRoute,
  ReceiptTokenRoute: ReceiptTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCardsPdfSha256Route: ApiCardsPdfSha256Route,
  ApiHooksEmailRoute: ApiHooksEmailRoute,
  ApiHooksUpRoute: ApiHooksUpRoute,
  ApiHooksWhatsappRoute: ApiHooksWhatsappRoute,
  ApiPdfsPdfSha256Route: ApiPdfsPdfSha256Route,
  ApiCardsPayTokenRoute: ApiCardsPayTokenRoute,
  ApiCardsReceiptTokenRoute: ApiCardsReceiptTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
