/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecurringBillsRouteImport } from './routes/recurring-bills'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HousematesRouteImport } from './routes/housemates'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUpWebhookRouteImport } from './routes/api.up-webhook'
import { Route as ApiEmailWebhookRouteImport } from './routes/api.email-webhook'
import { Route as ApiAiRouteImport } from './routes/api.ai'
import { Route as ApiSplatRouteImport } from './routes/api.$'
import { Route as ApiCronGenerateBillsRouteImport } from './routes/api.cron.generate-bills'
import { Route as ApiBillPdfsPdfSha256RouteImport } from './routes/api.bill-pdfs.$pdfSha256'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const RecurringBillsRoute = RecurringBillsRouteImport.update({
  id: '/recurring-bills',
  path: '/recurring-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HousematesRoute = HousematesRouteImport.update({
  id: '/housemates',
  path: '/housemates',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUpWebhookRoute = ApiUpWebhookRouteImport.update({
  id: '/api/up-webhook',
  path: '/api/up-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEmailWebhookRoute = ApiEmailWebhookRouteImport.update({
  id: '/api/email-webhook',
  path: '/api/email-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiRoute = ApiAiRouteImport.update({
  id: '/api/ai',
  path: '/api/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronGenerateBillsRoute = ApiCronGenerateBillsRouteImport.update({
  id: '/api/cron/generate-bills',
  path: '/api/cron/generate-bills',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillPdfsPdfSha256Route = ApiBillPdfsPdfSha256RouteImport.update({
  id: '/api/bill-pdfs/$pdfSha256',
  path: '/api/bill-pdfs/$pdfSha256',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/bills': typeof BillsRoute
  '/housemates': typeof HousematesRoute
  '/login': typeof LoginRoute
  '/recurring-bills': typeof RecurringBillsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/ai': typeof ApiAiRoute
  '/api/email-webhook': typeof ApiEmailWebhookRoute
  '/api/up-webhook': typeof ApiUpWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bill-pdfs/$pdfSha256': typeof ApiBillPdfsPdfSha256Route
  '/api/cron/generate-bills': typeof ApiCronGenerateBillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/bills': typeof BillsRoute
  '/housemates': typeof HousematesRoute
  '/login': typeof LoginRoute
  '/recurring-bills': typeof RecurringBillsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/ai': typeof ApiAiRoute
  '/api/email-webhook': typeof ApiEmailWebhookRoute
  '/api/up-webhook': typeof ApiUpWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bill-pdfs/$pdfSha256': typeof ApiBillPdfsPdfSha256Route
  '/api/cron/generate-bills': typeof ApiCronGenerateBillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/bills': typeof BillsRoute
  '/housemates': typeof HousematesRoute
  '/login': typeof LoginRoute
  '/recurring-bills': typeof RecurringBillsRoute
  '/api/$': typeof ApiSplatRoute
  '/api/ai': typeof ApiAiRoute
  '/api/email-webhook': typeof ApiEmailWebhookRoute
  '/api/up-webhook': typeof ApiUpWebhookRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/bill-pdfs/$pdfSha256': typeof ApiBillPdfsPdfSha256Route
  '/api/cron/generate-bills': typeof ApiCronGenerateBillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/bills'
    | '/housemates'
    | '/login'
    | '/recurring-bills'
    | '/api/$'
    | '/api/ai'
    | '/api/email-webhook'
    | '/api/up-webhook'
    | '/api/auth/$'
    | '/api/bill-pdfs/$pdfSha256'
    | '/api/cron/generate-bills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/bills'
    | '/housemates'
    | '/login'
    | '/recurring-bills'
    | '/api/$'
    | '/api/ai'
    | '/api/email-webhook'
    | '/api/up-webhook'
    | '/api/auth/$'
    | '/api/bill-pdfs/$pdfSha256'
    | '/api/cron/generate-bills'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/bills'
    | '/housemates'
    | '/login'
    | '/recurring-bills'
    | '/api/$'
    | '/api/ai'
    | '/api/email-webhook'
    | '/api/up-webhook'
    | '/api/auth/$'
    | '/api/bill-pdfs/$pdfSha256'
    | '/api/cron/generate-bills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  BillsRoute: typeof BillsRoute
  HousematesRoute: typeof HousematesRoute
  LoginRoute: typeof LoginRoute
  RecurringBillsRoute: typeof RecurringBillsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  ApiAiRoute: typeof ApiAiRoute
  ApiEmailWebhookRoute: typeof ApiEmailWebhookRoute
  ApiUpWebhookRoute: typeof ApiUpWebhookRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillPdfsPdfSha256Route: typeof ApiBillPdfsPdfSha256Route
  ApiCronGenerateBillsRoute: typeof ApiCronGenerateBillsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recurring-bills': {
      id: '/recurring-bills'
      path: '/recurring-bills'
      fullPath: '/recurring-bills'
      preLoaderRoute: typeof RecurringBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housemates': {
      id: '/housemates'
      path: '/housemates'
      fullPath: '/housemates'
      preLoaderRoute: typeof HousematesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/up-webhook': {
      id: '/api/up-webhook'
      path: '/api/up-webhook'
      fullPath: '/api/up-webhook'
      preLoaderRoute: typeof ApiUpWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/email-webhook': {
      id: '/api/email-webhook'
      path: '/api/email-webhook'
      fullPath: '/api/email-webhook'
      preLoaderRoute: typeof ApiEmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai': {
      id: '/api/ai'
      path: '/api/ai'
      fullPath: '/api/ai'
      preLoaderRoute: typeof ApiAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/generate-bills': {
      id: '/api/cron/generate-bills'
      path: '/api/cron/generate-bills'
      fullPath: '/api/cron/generate-bills'
      preLoaderRoute: typeof ApiCronGenerateBillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bill-pdfs/$pdfSha256': {
      id: '/api/bill-pdfs/$pdfSha256'
      path: '/api/bill-pdfs/$pdfSha256'
      fullPath: '/api/bill-pdfs/$pdfSha256'
      preLoaderRoute: typeof ApiBillPdfsPdfSha256RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  BillsRoute: BillsRoute,
  HousematesRoute: HousematesRoute,
  LoginRoute: LoginRoute,
  RecurringBillsRoute: RecurringBillsRoute,
  ApiSplatRoute: ApiSplatRoute,
  ApiAiRoute: ApiAiRoute,
  ApiEmailWebhookRoute: ApiEmailWebhookRoute,
  ApiUpWebhookRoute: ApiUpWebhookRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillPdfsPdfSha256Route: ApiBillPdfsPdfSha256Route,
  ApiCronGenerateBillsRoute: ApiCronGenerateBillsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
